"use client";
import { useEffect, useMemo, useState } from "react";
import { apiUrl } from "./api";

type Values = Record<string, number | null>;
type Snapshot = { id: string; month: string; data: Record<string, number>; updatedAt: string };
const empty: Values = {revenue:null,cost:null,expenses:null,companyCash:null,personalCash:null,familyAssets:null,investments:null,receivable:null,overdue:null,inventory:null,fixedAssets:null,companyDebt:null,personalDebt:null,incoming30:null,outgoing30:null,monthlyFixed:null};
const groups = [
  ["公司这个月赚了多少", [["revenue","本月收入"],["cost","产品或项目成本"],["expenses","工资及日常开支"],["receivable","客户还欠你的钱"],["overdue","其中已经逾期"],["inventory","库存价值"]]],
  ["现在有哪些钱和资产", [["companyCash","公司账户现金"],["personalCash","个人可用现金"],["familyAssets","家庭资产"],["investments","投资账户"],["fixedAssets","公司设备及资产"],["companyDebt","公司负债"],["personalDebt","个人及家庭负债"]]],
  ["未来30天的资金安排", [["incoming30","预计收款"],["outgoing30","必须付款"],["monthlyFixed","每月固定支出"]]],
] as const;

function money(n:number){const a=Math.abs(n||0);return (n<0?"−":"")+"¥"+(a>=10000?(a/10000).toFixed(a>=1000000?0:1)+"万":a.toLocaleString("zh-CN"))}
function currentMonth(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function monthName(m:string){const [y,mo]=m.split("-");return `${y}年${Number(mo)}月`}
function amount(values:Values,key:string){return values[key]??0}

export default function Dashboard({user,onSignOut,onUnauthorized}:{user:{displayName:string,email:string};onSignOut:()=>void;onUnauthorized:()=>void}){
  const [tab,setTab]=useState("overview"),[month,setMonth]=useState(currentMonth()),[values,setValues]=useState<Values>({...empty}),[snapshots,setSnapshots]=useState<Snapshot[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
  const hasCurrentSnapshot=snapshots.some(snapshot=>snapshot.month===month);
  const c=useMemo(()=>{const revenue=amount(values,"revenue"),cost=amount(values,"cost"),expenses=amount(values,"expenses"),companyCash=amount(values,"companyCash"),personalCash=amount(values,"personalCash"),receivable=amount(values,"receivable"),monthlyFixed=amount(values,"monthlyFixed"),profit=revenue-cost-expenses,cash=companyCash+personalCash,assets=cash+amount(values,"familyAssets")+amount(values,"investments")+receivable+amount(values,"inventory")+amount(values,"fixedAssets"),debts=amount(values,"companyDebt")+amount(values,"personalDebt"),net=assets-debts,margin=revenue?profit/revenue*100:0,runway=monthlyFixed?companyCash/monthlyFixed:0,debtRatio=assets?debts/assets*100:0,overdueRatio=receivable?amount(values,"overdue")/receivable*100:0;let score=100;if(runway<3)score-=25;else if(runway<6)score-=10;if(debtRatio>60)score-=25;else if(debtRatio>40)score-=10;if(profit<0)score-=25;else if(margin<10)score-=12;if(overdueRatio>30)score-=20;else if(overdueRatio>10)score-=8;return{profit,cash,assets,debts,net,margin,runway,debtRatio,overdueRatio,score:Math.max(0,score),ending:companyCash+amount(values,"incoming30")-amount(values,"outgoing30")}},[values]);
  useEffect(()=>{fetch(apiUrl("/snapshots"),{credentials:"include"}).then(async r=>{if(r.status===401){onUnauthorized();return{snapshots:[]}}if(!r.ok)throw new Error("数据加载失败");return r.json()}).then(res=>{const list:Snapshot[]=res.snapshots||[];setSnapshots(list);const found=list.find(x=>x.month===month);setValues(found?{...empty,...found.data}:{...empty})}).catch(()=>setMessage("数据加载失败，请刷新重试")).finally(()=>setLoading(false))},[onUnauthorized]);
  function chooseMonth(m:string){setMonth(m);const found=snapshots.find(x=>x.month===m);setValues(found?{...empty,...found.data}:{...empty})}
  async function save(){if(Object.values(values).some(value=>value===null)){setMessage("请先填写所有金额；没有该项请输入 0");return}setSaving(true);setMessage("");try{const r=await fetch(apiUrl("/snapshots"),{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({month,data:values})});const res=await r.json();if(r.status===401){onUnauthorized();throw new Error("登录状态已失效，请重新登录")}if(!r.ok)throw new Error(res.error||"保存失败");setSnapshots(old=>[res.snapshot,...old.filter(x=>x.month!==month)].sort((a,b)=>b.month.localeCompare(a.month)));setValues({...empty,...res.snapshot.data});setMessage("已安全保存到云端");setTab("overview")}catch(e){setMessage(e instanceof Error?e.message:"保存失败")}finally{setSaving(false)}}
  function update(key:string,value:string){setValues(v=>({...v,[key]:value===""?null:Math.max(0,Number(value))}))}
  const tasks=[] as string[];if(amount(values,"overdue")>0)tasks.push(`催收逾期款 ${money(amount(values,"overdue"))}`);if(c.runway<6)tasks.push(`补足现金安全垫，还差 ${money(Math.max(0,amount(values,"monthlyFixed")*6-amount(values,"companyCash")))}`);if(c.margin<15)tasks.push("检查本月金额最大的三项成本费用");if(c.debtRatio>40)tasks.push("暂停新增借款，优先降低负债");if(tasks.length<3)tasks.push("确认未来30天收付款计划");if(tasks.length<3)tasks.push("安排可分配资金，先留安全垫再分红");
  if(loading)return <main className="loading">正在打开你的财富驾驶舱…</main>;
  return <div className="app"><aside><div className="brand"><b>财</b><span>老板财富驾驶舱</span></div><nav>{[["overview","财富总览"],["input","更新数字"],["history","历史月份"],["guide","使用指南"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="account"><span>{user.displayName}</span><small>{user.email}</small><a href="/" onClick={e=>{e.preventDefault();onSignOut()}}>退出登录</a></div></aside><main className="workspace"><header><div><p className="eyebrow">{monthName(month)} · 财富健康简报</p><h1>{tab==="overview"?"老板，今天的钱，心里有数。":tab==="input"?"更新关键数字":tab==="history"?"历史月份记录":"老板使用指南"}</h1></div><div className="header-actions"><input aria-label="选择月份" type="month" value={month} onChange={e=>chooseMonth(e.target.value)}/>{tab==="overview"&&<button className="primary" onClick={()=>setTab("input")}>更新本月数字</button>}</div></header>{message&&<div className="notice">{message}</div>}
  {tab==="overview"&&(hasCurrentSnapshot?<><div className="status"><i></i><b>{c.score>=80?"整体安全":c.score>=60?"需要关注":"存在风险"}</b><span>数据已按账号独立保存，可随时继续使用。</span></div><section className="metrics"><article><span>你真正拥有的财富</span><strong>{money(c.net)}</strong><small>总资产减去全部欠款</small></article><article><span>公司本月真正赚到</span><strong>{money(c.profit)}</strong><small>净利润率 {c.margin.toFixed(1)}%</small></article><article><span>手头可立即使用的钱</span><strong>{money(c.cash)}</strong><small>公司与个人可用现金</small></article><article><span>别人还欠你的钱</span><strong>{money(amount(values,"receivable"))}</strong><small className="danger">逾期 {money(amount(values,"overdue"))}</small></article></section><section className="dashboard-grid"><article className="card"><div className="card-title"><div><h2>财富安全分</h2><p>现金、负债、利润和回款的综合结果</p></div></div><div className="score-layout"><div className="score" style={{background:`conic-gradient(#1e6b50 ${c.score}%,#e5ebe7 0)`}}><div><b>{c.score}</b><small>满分100</small></div></div><ul><li className={c.runway>=6?"ok":"warn"}>现金可支撑 {c.runway.toFixed(1)} 个月</li><li className={c.margin>=10?"ok":"warn"}>净利润率 {c.margin.toFixed(1)}%</li><li className={c.debtRatio<=40?"ok":"warn"}>负债占资产 {c.debtRatio.toFixed(1)}%</li><li className={c.overdueRatio<=10?"ok":"warn"}>逾期占应收 {c.overdueRatio.toFixed(1)}%</li></ul></div></article><article className="card dark"><div className="card-title"><div><h2>老板本周只做这3件事</h2><p>按风险和影响自动排序</p></div></div><ol>{tasks.slice(0,3).map((t,i)=><li key={t}><b>{i+1}</b><span>{t}</span></li>)}</ol></article><article className="card"><div className="card-title"><div><h2>未来30天，钱够不够用</h2><p>预计月底余额 {money(c.ending)}</p></div></div><div className="cash-flow"><div><span>现在有</span><b>{money(amount(values,"companyCash"))}</b></div><div><span>预计收回</span><b>{money(amount(values,"incoming30"))}</b></div><div><span>必须付出</span><b>{money(amount(values,"outgoing30"))}</b></div></div><div className="bar"><span style={{width:`${Math.min(100,c.runway/6*100)}%`}}></span></div></article><article className="card"><div className="card-title"><div><h2>本月的钱是怎么留下来的</h2><p>收入减去成本和日常开支</p></div></div><div className="money-flow"><div><span>卖出去</span><b>{money(amount(values,"revenue"))}</b></div><div><span>花出去</span><b>−{money(amount(values,"cost")+amount(values,"expenses"))}</b></div><div><span>最后留下</span><b>{money(c.profit)}</b></div></div></article></section></>:<section className="card empty overview-empty"><b>还没有财富数据</b><p>先录入你的收入、现金、资产和负债，<br/>WealthFlow 才能生成你的财富健康简报。</p><button className="primary" onClick={()=>setTab("input")}>开始录入</button></section>)}
  {tab==="input"&&<section className="card form-card">{groups.map(([title,items],i)=><div className="form-section" key={title}><h2>{i+1}. {title}</h2><div className="form-grid">{items.map(([key,label])=><label key={key}><span>{label}</span><div><i>¥</i><input type="number" min="0" inputMode="decimal" placeholder="请输入金额" value={values[key]??""} onChange={e=>update(key,e.target.value)}/></div></label>)}</div></div>)}<div className="form-actions"><span>保存后可在任何设备登录查看</span><button className="primary" disabled={saving} onClick={save}>{saving?"正在保存…":"保存本月数据"}</button></div></section>}
  {tab==="history"&&<section className="card"><div className="card-title"><div><h2>历史财富记录</h2><p>每个月保存一次，才能看见财富变化</p></div><button onClick={()=>window.print()}>打印当前报告</button></div>{snapshots.length?<div className="history-list">{snapshots.map(s=>{const p=s.data.revenue-s.data.cost-s.data.expenses;return <button key={s.id} onClick={()=>{chooseMonth(s.month);setTab("overview")}}><span><b>{monthName(s.month)}</b><small>更新于 {new Date(s.updatedAt).toLocaleDateString("zh-CN")}</small></span><span><small>本月利润</small><b>{money(p)}</b></span><span><small>公司现金</small><b>{money(s.data.companyCash)}</b></span><em>查看 →</em></button>})}</div>:<div className="empty"><b>还没有历史记录</b><p>录入并保存本月数据后，这里会自动形成月份档案。</p><button className="primary" onClick={()=>setTab("input")}>去录入本月数据</button></div>}</section>}
  {tab==="guide"&&<section className="guide-grid"><article className="card"><h2>每周15分钟，只问5个问题</h2>{["今天真正能动用多少钱？","未来30天预计收多少、必须付多少？","哪些客户的钱已经逾期？","这个月真正赚了多少钱？","现在最该催款、降本，还是暂停投资？"].map((x,i)=><p className="guide-item" key={x}><b>{i+1}</b>{x}</p>)}</article><article className="card"><h2>三条资金纪律</h2><p className="rule"><b>公私分开</b>个人消费不从公司账户直接支付。</p><p className="rule"><b>先留后分</b>预留安全资金后，再考虑分红。</p><p className="rule"><b>大钱先算</b>投入前先算多久收回、最坏损失多少。</p></article></section>}
  </main></div>
}
